# Base image
FROM nvidia/cuda:12.2.0-devel-ubuntu20.04

# Set working directory
WORKDIR /workspace

# Install necessary packages
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get upgrade -y && apt-get install -y \
    build-essential \
    curl \
    git \
    wget \
    vim \
    unzip \
    python3-pip  \
    g++ \
    sudo && \
    rm -rf /var/lib/apt/lists/*

RUN wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb && \
    sudo dpkg -i packages-microsoft-prod.deb && \
    sudo apt-get install -y apt-transport-https dotnet-sdk-5.0

# Install VSCode
RUN curl -fsSL https://code-server.dev/install.sh | sh

# Install Remote Development extension
RUN /usr/bin/code-server \
        --install-extension ms-vscode-remote.vscode-remote-extensionpack \
        --install-extension "ms-python.python" \ 
        --install-extension "ms-toolsai.jupyter"

# Set CUDA environment variables
ENV PATH="/usr/local/cuda-11.4/bin:${PATH}"
ENV LD_LIBRARY_PATH="/usr/local/cuda-11.4/lib64:${LD_LIBRARY_PATH}"

# Set the root password for VSCode
RUN echo "root:root" | chpasswd && \
    sed -i 's|password:.*|password: root|g' ~/.config/code-server/config.yaml

# Expose code-server port
EXPOSE 8080

RUN git clone https://github.com/SagiK-Repository/DeepLearning.git /workspace

# Git clone & Start code-server
CMD git push && \
    code-server --bind-addr 0.0.0.0:8080 .